services:
  steamcmd:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
      args:
        - BUILDKIT_INLINE_CACHE=1
      cache_from:
        - mbround18/steamcmd:base-cache
    image: mbround18/steamcmd:base-${VERSION:-latest}
    restart: no

  steamcmd-wine:
    build:
      context: .
      dockerfile: Dockerfile
      target: wine
      args:
        - BUILDKIT_INLINE_CACHE=1
      cache_from:
        - mbround18/steamcmd:wine-cache
    image: mbround18/steamcmd:wine-${VERSION:-latest}
    restart: no

  steamcmd-proton:
    build:
      context: .
      dockerfile: Dockerfile
      target: proton
      args:
        - BUILDKIT_INLINE_CACHE=1
      cache_from:
        - mbround18/steamcmd:proton-cache
    image: mbround18/steamcmd:proton-${VERSION:-latest}
    restart: no
