name: Docker Release

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker-release:
    strategy:
      fail-fast: false
      matrix:
        target: [base, wine, proton]
    uses: mbround18/gh-reusable/.github/workflows/docker-release.yaml@main
    with:
      image: "mbround18/steamcmd"
      target: "${{ matrix.target }}"
      prepend_target: true
    secrets: inherit

  tagger:
    needs: docker-release
    if: ${{ github.ref == 'refs/heads/main' }}
    uses: mbround18/gh-reusable/.github/workflows/tagger.yaml@main
    secrets: inherit
