name: Docker Release

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker-release:
    strategy:
      fail-fast: false
      matrix:
        target: [steamcmd, steamcmd-wine, steamcmd-proton]
    uses: mbround18/gh-reusable/.github/workflows/docker-release.yaml@main
    with:
      image: "mbround18/steamcmd-bases"
      target: "${{ matrix.target }}"
    secrets: inherit

  tagger:
    uses: mbround18/gh-reusable/.github/workflows/tagger.yaml@main
    secrets: inherit
